- apt:
    pkg:
      - nginx-full
      - libnginx-mod-rtmp


- file:
    path: "/var/www/{{ nginx_rtmp.stream_secret }}/hls"
    group: www-data 
    owner: www-data
    state: directory

- file:
    path: "/var/www/{{ nginx_rtmp.stream_secret }}/dsh"
    group: www-data 
    owner: www-data
    state: directory

- name: update nginx configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: 
    - reload nginx
  loop:
    - src: "nginx.conf.j2"
      dest: "/etc/nginx/nginx.conf"
    - src: "site-default.j2"
      dest: "/etc/nginx/sites-available/default"
  loop_control:
    label: "{{ item.src }}"

- name: update index.html
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    owner: "www-data"
    group: "www-data"

- name: update shaka index.html
  template:
    src: "shaka-index.html.j2"
    dest: "/var/www/html/shaka-index.html"
    owner: "www-data"
    group: "www-data"

- name: update dash index.html
  template:
    src: "dashref-index.html.j2"
    dest: "/var/www/html/dashref-index.html"
    owner: "www-data"
    group: "www-data"


- name: update hls index.html
  template:
    src: "hls-index.html.j2"
    dest: "/var/www/html/hls-index.html"
    owner: "www-data"
    group: "www-data"


- name: upload website assets
  copy:
    src: "{{ item.src }}"
    dest: "/var/www/html/"
    owner: "www-data"
    group: "www-data"
  loop:
    - src: "dash.all.min.js"    
    - src: "video-js.min.css"
    - src: "video.min.js"
    - src: "videojs-http-streaming.min.js"
    - src: "videojs-dash.min.js"
    - src: "shaka-player.compiled.js"
  loop_control:
    label: "{{ item.src }}"

- name: setup mimetypes
  lineinfile:
    path: /etc/nginx/mime.types
    line: "{{ item.line }}"
    insertbefore: "^.*}"
  loop:
    - line: "\tapplication/vnd.apple.mpegurl m3u8;"
    - line: "\tvideo/mp2t ts; "
  notify: 
    - reload nginx
  