---
- hosts: dev
  vars:
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: 
      - nginx  
    certbot_auto_renew: true
    certbot_auto_renew_user: www-data
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
  roles:
    - ubuntu_base
    - nginx_rtmp
    - geerlingguy.certbot